### ISSUE TITLE
exporting to table

### ISSUE THREAD

**Issue by ghost** [linktohack/ox-latex-subfigure#1]
Hello,

I tried ox-latex-subfigure today. I loaded it with the code you provided  and tried your minimal example,
changing path of both of course.  It still exports to table...
What am I doing wrong?
\begin{table}[!htbp]
\caption{\label{fig:hello}
Use figure/subfigure instead of tabular, remember to set \texttt{:environment}}
\begin{subfigure}{0.4\textwidth}{c}
\includegraphics{/home/mcg/picture1.jpg} & \includegraphics{/home/mcg/picture2.jpg}\
tttttt & zzzzzz\
\end{subfigure}
\end{table}
\end{document}

**Comment by linktohack** [comment]
Hi @miguelazo82, I forgot that I have `org-latex-caption-above` set to `nil`. You can try the minimal working `init.el` bellow. I will update the README, too.

``` emacs-lisp
(package-initialize)
(use-package ox-latex-subfigure
  :init
  (setq org-latex-caption-above nil)
  :load-path "~/Dropbox/ProjectWeekends/lisp/ox-latex-subfigure/"
  :config (require 'ox-latex-subfigure))
```

**Comment by linktohack** [comment]
Also remember to have `subcaption` package included, please check `README.org`.

**Comment by ghost** [comment]
Hi Quang-Linh,

thank you for your quick reply.
Yes it works like that, but I would have two more issues:
- With (setq org-latex-caption-above nil) how can I turn on table 
  captions above on a per-table basis?
- Is there any way to pass arguments to \includegraphics: the width of 
  the graphics cannot be influenced, which would mean that I have to 
  resize them outside LaTeX...

Greetings and thank you again,

Michael

**Comment by ghost** [comment]
Hello again,

I found that I can set the width simply putting using latex code in the 
table:
   \includegraphics[width = .9\linewidth]{../picture/renex.jpg}
Then I do not have a clickable link anymore,  but no problem...

I did quite some search but do not seem to find how to set the 
org-latex-caption-above on a per float basis...

All the best,

Michael

**Comment by linktohack** [comment]
Michael,

Code updated with respect to `org-latex-caption-above`. About the subfigure width, it is the default value from `org-latex-image-default-width` which is `".9\\linewidth"`. If you want to set it to a different value, you can have a look on `#+BIND:` keyword [1](http://orgmode.org/manual/Export-settings.html), also remember to set `org-export-allow-bind-keywords` to non-nil.

**Comment by ghost** [comment]
I see now that I did have the image-default-width variable modified - that was my mistake... 

But having to set org-latex-caption-above to nil globally is a problem, as the format demanded needs table captions to be on top.  
I see #+BIND  could only change this option buffer-wide but not per float.
Is there any way to implement this without having to change this option?

**Comment by linktohack** [comment]
The easiest way should be a second #+BIND after the environment, it you still need this option, feel free to add an option here [1](https://github.com/linktohack/ox-latex-subfigure/blob/7ba83c6229ee13bd84c81392b824e8e18b940df4/ox-latex-subfigure.el#L16) and a `replace-regex` some where here [2](https://github.com/linktohack/ox-latex-subfigure/blob/7ba83c6229ee13bd84c81392b824e8e18b940df4/ox-latex-subfigure.el#L63). A pull request is welcome :+1:

**Comment by linktohack** [comment]
Anyway, `org-latex-caption-above` is no longer need to be set to nil.

**Comment by ghost** [comment]
Sorry for bothering.  I had downloaded the new git-version, reloaded the package and it did not work. Restarting emacs helped, will do that in the future before posting here....

Now it works perfectly - nice work and thank you very much.  No need for #+BIND and adding hacking an option in the code - would not have had a clue how to do that anyway...

**Comment by linktohack** [comment]
Ok, glad it helps, Michael.
