### ISSUE TITLE
Setting subfigure width

### ISSUE THREAD

**Issue by tdehaeze** [linktohack/ox-latex-subfigure#14]
Hi,
First of all, thank you for this package, very useful! :)

I would like to be able to tune the size of the subfigures, ideally individually, but at least setting one default size.

For now, it seems it takes the default width defined by =org-latex-image-default-option=  or =org-latex-image-default-width=.

Can I tune that for subfigures? Like having one variable =org-latex-subfigure-width=?

Thanks

**Comment by linktohack** [comment]
Thanks @tdehaeze, should be fixed by https://github.com/linktohack/ox-latex-subfigure/commit/0a5d3ecc264a481b96126d0c9865f48da19d3018

**Comment by tdehaeze** [comment]
Sorry, I and quite a lisp noob. I am not sure what should I write in my org-mode file to tune the width of my subfigures.
I used to do that:
```
#+name: fig:force_deflection_characteristics
#+caption: Force-deflection characteristics
#+attr_latex: :environment subfigure :width 0.32\linewidth :align t
| file:material_histeresis.png                    | file:dry_friction.png             | file:viscous_damper.png               |
| <<fig:material_histeresis>> Material hysteresis | <<fig:dry_friction>> Dry friction | <<fig:viscous_damper>> Viscous damper |
```

It seems setting the height using:
`#+attr_latex: :environment subfigure :height 3cm :align t` does not seems to work.

Could you provide an example of what you implemented?

Thanks

**Comment by linktohack** [comment]
Please see https://github.com/linktohack/ox-latex-subfigure/issues/19#issuecomment-512905980

**Comment by tdehaeze** [comment]
Thanks, this is working fine.
