### ISSUE TITLE
Add this package to MELPA

### ISSUE THREAD

**Issue by conao3** [linktohack/ox-latex-subfigure#15]
Hi!
I like this package. Do you have an idea to add this package to MELPA?
Registering with MELPA allows more Emacs users to use this package.

If you think it is troublesome, I will Fork and register. If you don't like having too many repositories, you can help with ongoing maintenance by making me a collaborator.

Best,

**Comment by linktohack** [comment]
Adressed by https://github.com/melpa/melpa/pull/6302

Of course will be happy to have contributors.

**Comment by conao3** [comment]
Good, thanks!

**Comment by conao3** [comment]
I accept the invitation 🎉 
I manage issue and PR, and all code changes go through PR procedures.
Thank you for inviting me!

**Comment by linktohack** [comment]
Thanks @conao3
