### ISSUE TITLE
Caption / shortcaption export not working

### ISSUE THREAD

**Issue by ghost** [linktohack/ox-latex-subfigure#2]
When exporting normal figures I can insert a shortcaption for the table of figures (whole caption looks pretty bad there. 
With subfigure this does not work. When inserting #+caption[short]long then neither gets exported. 
I tried with  
# +ATTR_LATEX: :caption \caption[short]long

and also no luck...

Minimal example:
# +CAPTION[This short caption exports well]: Longcaption
# +LABEL: fig:figure

figure 1                             
# +CAPTION[Short caption]: Long caption that is so long that it does not fit or look good in the table of figures, needing a short caption for that...
# +LABEL: fig:subfigure_example1
# +ATTR_LATEX: :environment subfigure :width 0.49\linewidth :align b

| This is a subcation of the first image | This is a subcaption of the second image. |
| figure 1                               | figure 2                                  |

**Comment by linktohack** [comment]
Should be fixed, please pull the latest version...

**Comment by ghost** [comment]
Fixed - thank you very much again!

**Comment by linktohack** [comment]
You're welcome :)
