### ISSUE TITLE
Export without \centering (with my setup)

### ISSUE THREAD

**Issue by ghost** [linktohack/ox-latex-subfigure#3]
In my org-mode setup I need to have the option "Org Latex Tables Centered" disabled, because of issues when using threeparttable and sidewaystable (see link)
https://www.mail-archive.com/emacs-orgmode@gnu.org/msg104079.html

To still center all float environments I inserted: 
# +LATEX_HEADER: \makeatletter
# +LATEX_HEADER: \g@addto@macro\@floatboxreset\centering
# +LATEX_HEADER: \makeatother

But this does not work with ox-latex-subfigure, and :align option only allows for t,c,b
Is there some possibility to get \centering on export with "Org Latex Tables Centered" disabled?
Or could you indicate what to change in your code to get that behaviour (I see \centering at various points, but do not know where to change it). In my use case I would always center align, so no need for any conditional....

**Comment by linktohack** [comment]
The hook/filter function only does search/replace etc at table level at the moment. I'd like to have a better approach actually.

Anyway can you post here a minimal example with actual and desired result?

**Comment by ghost** [comment]
*\* Output with actual configuration

#+begin_src emacs-lisp 
(setq org-latex-tables-centered nil)
#+end_src

#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \g@addto@macro\@floatboxreset\centering
#+LATEX_HEADER: \makeatother

#+CAPTION[short caption]: NORMAL FIGURE
#+LABEL: fig:figure
[[~/thesis/figure/a.pdf]]

BECOMES:
\begin{figure}[!htbp]
\centering
\includegraphics{/home/mcg/thesis/figure/a.pdf}
\caption[short caption]{\label{fig:figure}
long caption}
\end{figure}

#+CAPTION[short caption]: SUBFIGURE
#+LABEL: fig:subfigure
#+ATTR_LATEX: :environment subfigure :width 0.49\linewidth :align b 
| subcation a)          | subcaption b)         |
| [[~/thesis/figure/a.pdf]] | [[~/thesis/figure/b.pdf]] |

BECOMES (no \centering)

\begin{figure}[!htbp]
\caption[short caption]{\label{fig:subfigure}
long caption}
\begin{subfigure}[b]{0.49\linewidth}
\includegraphics{/home/mcg/thesis/figure/a.pdf}
\caption{subcation a)}
\end{subfigure}
\begin{subfigure}[b]{0.49\linewidth}
\includegraphics{/home/mcg/thesis/figure/b.pdf}
\caption{subcaption b)}
\end{subfigure}
\end{figure}

*\* Desired output

Only with org-latex-tables-centered enabled I get the right output - but that is not an option for me...

#+begin_src emacs-lisp 
(setq org-latex-tables-centered t)
#+end_src

#+CAPTION[short caption]: long caption
#+LABEL: fig:subfigure
#+ATTR_LATEX: :environment subfigure :width 0.49\linewidth :align b 
| subcation a)          | subcaption b)         |
| [[~/thesis/figure/a.pdf]] | [[~/thesis/figure/b.pdf]] |

\begin{figure}[!htbp]
\caption[short caption]{\label{fig:subfigure}
long caption}
\centering
\begin{subfigure}[b]{0.49\linewidth}
\includegraphics{/home/mcg/thesis/figure/a.pdf}
\caption{subcation a)}
\end{subfigure}
\begin{subfigure}[b]{0.49\linewidth}
\includegraphics{/home/mcg/thesis/figure/b.pdf}
\caption{subcaption b)}
\end{subfigure}
\end{figure}

As I said, for me it would be enough to use centering for all cases, no need for a condition.  I know mine is a special case, as usually you would just turn on org-latex-tables-centered.  But that option conflicts with threeparttable...
So any indication on how to modify the code for my use case would be welcome if you do not want to include another option.    For now, I just do not understand why  \g@addto@macro\@floatboxreset\centering does not center it anyway.

**Comment by linktohack** [comment]
I see, let's try to replace the default value here https://github.com/linktohack/ox-latex-subfigure/blob/master/ox-latex-subfigure.el#L31 from `(centering "")` to `(centering "\\centering\n")` to see if it works for you...

**Comment by ghost** [comment]
\centering now gets inserted.  Thank you!

But I notice now that this was not even causing the problem,
My graph gets off center, because one is wider than the other, and 
apparantly within the subfigure environment it gets left aligned.

Which brings me to another question: (or should I open a new issue?)

Do you think it would be possible to somehow include several :width 
statements, for each subfigure, to get different sized subfigures? This 
came up now, as until now all subfigures were of the same width...)
Or is that too complicated to implement?

All the best,

**Comment by linktohack** [comment]
It's not too complicated to include a list of width etc but then it will be a little messy. A cleaner solution maybe just include a LaTeX fragment/block?

**Comment by ghost** [comment]
I kind of found a solution to off-centered figures, just now: 
Adding \centering in front of the file:link in the table adds \centering within the subfigure environment, which also resolves my problem for now and could (for my case again) be the default behaviour.  
And you are right; for the more specific cases then I will take the LaTeX code block...

((string-match "^\\begin{subfigure}\({\(._?\)}\)?\({\(._?\)}\)?" row)
Could I add \n \centering\n" in this line to make it default? But where? Thanks again...

**Comment by linktohack** [comment]
Glad you find a solution. You can insert after this line, (and before `%s`) https://github.com/linktohack/ox-latex-subfigure/blob/9749ee16e164ebf9e3c73bbd4317f9718aaf8b49/ox-latex-subfigure.el#L79

**Comment by ghost** [comment]
Everything working, nice! Thank you very much again once more...

**Comment by linktohack** [comment]
Nice, you may also interested in https://github.com/linktohack/synorg, a syntex-like feature but work directly with org mode...

**Comment by ghost** [comment]
That looks fine; I have a look these days - does it also work with external pdf viewer (evince)? - just curious, if not the internal one is fine...

**Comment by linktohack** [comment]
You need to configure the AUCTeX to use Evince as an external viewer, but it should. Working fine for me with Skim on OSX (there are some limitations though...)

**Comment by ghost** [comment]
OK - I think I have that configured already... I'll sure give it a try, 
that's been bothering me for  a long time to always have to search in 
the org-mode / pdf...

**Comment by linktohack** [comment]
OK, cool, I'm closing this
