### ISSUE TITLE
Export breaks with wrong-type-argument integer-or-marker-p nil

### ISSUE THREAD

**Issue by jandt** [linktohack/ox-latex-subfigure#6]
Sorry if i am doing something stupid.
I loaded ox-latex-subfigure and created a little table analog to the README:
    
    #+NAME: fig:nogora
    #+CAPTION: Blablabla
    #+ATTR_LATEX: :environment subfigure :width 0.4\textwidth :align c
    | file:../nogora/ecalhisto.pdf | file:../nogora/ecalhisto-cut.pdf |

When exporting (i.e. C-e l l) I get the error message "wrong-type-argument integer-or-marker-p nil".

It seems to refer to the call to `text-properties-at` in line 12. of the .el file, with `pt` being nil.

Below is the backtrace:

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  text-properties-at(nil "\\begin{center}\n\\begin{subfigure}{0.4\\textwidth}{c}\n\\begin{center}\n\\includegraphics[width=.9\\linewidth]{../nogora/ecalhisto.pdf}\n\\end{center} & \\begin{center}\n\\includegraphics[width=.9\\linewidth]{../nogora/ecalhisto-cut.pdf}\n\\end{center}\\\\\n\\end{subfigure}\n\\end{center}\n\n")
  (plist-get (text-properties-at pt text) :parent)
  (setq pt (next-property-change pt text) cell (plist-get (text-properties-at pt text) :parent) table (org-export-get-parent-table cell))
  (while (or (not table) (not pt)) (setq pt (next-property-change pt text) cell (plist-get (text-properties-at pt text) :parent) table (org-export-get-parent-table cell)))
  (let ((pt 0) cell table attr env limit) (while (or (not table) (not pt)) (setq pt (next-property-change pt text) cell (plist-get (text-properties-at pt text) :parent) table (org-export-get-parent-table cell))) (setq attr (org-export-read-attribute :attr_latex table) env (plist-get attr :environment) limit (string-to-int (or (plist-get attr :limit) "0"))) (if (not (string= "subfigure" env)) text (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert text) (goto-char 1) (link/latex-table-to-subfigure limit) (buffer-string)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))))
  (progn (let ((pt 0) cell table attr env limit) (while (or (not table) (not pt)) (setq pt (next-property-change pt text) cell (plist-get (text-properties-at pt text) :parent) table (org-export-get-parent-table cell))) (setq attr (org-export-read-attribute :attr_latex table) env (plist-get attr :environment) limit (string-to-int (or (plist-get attr :limit) "0"))) (if (not (string= "subfigure" env)) text (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert text) (goto-char 1) (link/latex-table-to-subfigure limit) (buffer-string)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))))
  (if (org-export-derived-backend-p backend (quote latex)) (progn (let ((pt 0) cell table attr env limit) (while (or (not table) (not pt)) (setq pt (next-property-change pt text) cell (plist-get (text-properties-at pt text) :parent) table (org-export-get-parent-table cell))) (setq attr (org-export-read-attribute :attr_latex table) env (plist-get attr :environment) limit (string-to-int (or (plist-get attr :limit) "0"))) (if (not (string= "subfigure" env)) text (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ... ...) (and ... ...))))))))
  link/org-export-table-to-subfigure("\\begin{center}\n\\begin{subfigure}{0.4\\textwidth}{c}\n\\begin{center}\n\\includegraphics[width=.9\\linewidth]{../nogora/ecalhisto.pdf}\n\\end{center} & \\begin{center}\n\\includegraphics[width=.9\\linewidth]{../nogora/ecalhisto-cut.pdf}\n\\end{center}\\\\\n\\end{subfigure}\n\\end{center}\n\n" latex (:export-options nil :back-end [cl-struct-org-export-backend latex nil ((bold . org-latex-bold) (center-block . org-latex-center-block) (clock . org-latex-clock) (code . org-latex-code) (drawer . org-latex-drawer) (dynamic-block . org-latex-dynamic-block) (entity . org-latex-entity)
...

**Comment by jandt** [comment]
Aaargh. Sorry.

Obviously it does not work with leaving out the table row for the captions. Inserted. Works.

(The subfigure environment does not need \caption{bla}, but obviously the org export parser needs those table cells.)

Pleease close the issue and forgive me for spamming you. And thanks for creating this code.

ps:
On second thought, actually it would be nice to be able to use subfigure environments without captions on the individual subfigures in some cases, (empty caption still produces sublabels), but this is no real problem. Thanks a lot for your package.

**Comment by linktohack** [comment]
Thanks for the suggestion, the package is working fine for my need at the moment but I will consider this.
