### ISSUE TITLE
ox-latex-subfigure stopped working in org-mode 9.

### ISSUE THREAD

**Issue by ghost** [linktohack/ox-latex-subfigure#7]
Only the captions were updated but no figures were exported. So I updated today.  
Now I only get the error message: 

if: Search failed: "\\\\\\\\
?"

**Comment by eoma** [comment]
Could you add a text sample (a minimum working example)?

**Comment by eoma** [comment]
At least, if you use the latest available version ox-latex-subfigure, which version of emacs and org-mode are you using? This information could could be useful in order to reproduce the issue.

**Comment by ghost** [comment]
Minimal working example from the readme produces the error as well: no latex export. 
Message: 
if: Search failed: "\\\\\\\\
?"

Org mode version 9.0.1 (9.0.1-elpaplus @ /home/mcg/.emacs.d/elpa/org-plus-contrib-20161118/)

#+LATEX_HEADER: \usepackage{subcaption}
#+NAME: fig:hello
#+CAPTION: Use figure/subfigure instead of tabular, remember to set =:environment=
#+ATTR_LATEX: :environment subfigure :width 0.4\textwidth :align c
| [[~/Desktop/figure_1.png]] | <<fig:hello_subfigure>> tttttt |
| zzzzz                      | [[~/Desktop/figure_1.png]]     |

**Comment by eoma** [comment]
I am not able to reproduce, even with a clean .emacs.d and only use-package and org-mode installed.

**Comment by ghost** [comment]
OK. Now I renamed my initfile and loaded with default settings. Then it 
works. With the setup in my init file it used to work great. I'll try to 
find out what is causing it...

Any idea what the error message means?

**Comment by ghost** [comment]
I finally found the cause: in my init-file (.customizedbyemacs file to 
be precise) I have
  '(org-latex-tables-booktabs t)
enabled. Turning it off solves the problem.

Minimum (non-) working example
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{booktabs}

#+BEGIN_SRC emacs-lisp
(setq org-latex-tables-booktabs t)
#+END_SRC


#+CAPTION: test
#+LABEL: fig:someLabel
#+ATTR_LATEX: :environment subfigure :width 0.49\linewidth :align c
| [[file:anyfile]] | [[file:anotherfile]] |
| test A       | test B           |

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

I can just work around it by enabling booktabs in manually in all the 
other tables. Being able to fix it would save me that work of course 
(quite a lot of tables...)

**Comment by eoma** [comment]
Ah, sorry for the late update. The solution is to remove inserted (top|mid|bottom)rules before collapsing
multiline rows to single line rows. I will push a solution later today.

**Comment by eoma** [comment]
Take a look at #8 and see if that fixes the issue.

**Comment by linktohack** [comment]
Thanks @eoma for the PR.

**Comment by ghost** [comment]
Fixed, perfect! Thank you very much.

Closed...
