### ISSUE TITLE
brakes table.el

### ISSUE THREAD

**Issue by ghost** [linktohack/ox-latex-subfigure#9]
Hello. Thank you very much for your package.
I want to let you know that it is currently braking my table.el for some reasons. I commented the sections of my .emacs where ox-latex-subfigure is, and table.el is working again. I get a `wrong-type-argument integer-or-marker-p nil` . I checked the issues in the repo, and I don't think that it's the same as https://github.com/linktohack/ox-latex-subfigure/issues/6
 
I'm attaching my configuration for org-mode.
[org-mode.txt](https://github.com/linktohack/ox-latex-subfigure/files/1006619/org-mode.txt)

**Comment by linktohack** [comment]
@broncodev it should be fixed by the latest commit. Please try again and let me know if it work for you.

**Comment by ghost** [comment]
Yep! Solved. Thank you very much! :)
